---

- hosts: all
  tasks:
    - name: cria chave ssh do usuário local, caso não exista
      local_action:
        module: user
        name: "{{ lookup('env','LOGNAME') }}"
        generate_ssh_key: yes
      run_once: True
      register: "usuario_local"

    - name: limpa registros do IP no known_hosts local
      local_action:
        module: known_hosts
        name: "{{ ip|default(ansible_host) }}"
        state: absent

    - name: adiciona host no .ssh/config local
      local_action:
        module: blockinfile
        path: '~/.ssh/config'
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ ansible_hostname }} -->"
        block: |
          Host {{ ansible_hostname }} {{ ansible_hostname }}.local {{ grupo }}-{{ansible_hostname }}
          Hostname {{ ip|default(ansible_host) }}
          User root
          StrictHostKeyChecking accept-new

- hosts: all
  become: true
  roles:
    - vagrant

