---

- name: cria chaves do root
  user:
    name: root
    generate_ssh_key: yes

- name: permite login por senha
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'

- name: permite acesso por ssh externo
  authorized_key:
    user: root
    state: present
    key: "{{ usuario_local.ssh_public_key }}"

- name: tarefas específicas de distribuição
  include_tasks: "{{ ansible_facts['distribution_file_variety'] }}.yml"
