---

- name: resolução de nomes entre VMs (Debian)
  include_tasks: Debian-family.yml
  when:
    - ansible_facts['distribution_file_variety'] == "Debian"
    - ansible_facts['distribution_major_version']|int >= 8

- name: resolução de nomes entre VMs (RedHat)
  include_tasks: RedHat-family.yml
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - ansible_facts['distribution_major_version']|int >= 6

- name: cria chaves do root
  user:
    name: root
    generate_ssh_key: yes

- name: permite login por senha
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'

- name: permite acesso por ssh externo
  authorized_key:
    user: root
    state: present
    key: "{{ usuario_local.ssh_public_key }}"
