---

- assert:
    that: ansible_facts['distribution_major_version']|int >= 6
    fail_msg: "apenas para RHEL/CentOS >= 6"
    quiet: true

- name: instala EPEL
  yum:
    name: epel-release
    state: latest
  when: ansible_distribution == 'CentOS'

- name: instala avahi
  yum:
    name: avahi
    state: latest

- name: instala nss-mdns
  yum:
    name: nss-mdns
    state: latest

- name: inicia avahi-daemon
  service:
    name: avahi-daemon
    state: started
    # o serviço já vem habilitado

- name: atualiza todos os pacotes
  yum:
    name: '*'
    state: latest

- name: desabilita selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: configurações gerais de shell interativo
  blockinfile:
    path: /etc/profile.d/sh.local
    block: |
      export PAGER=less
      export PS1='[\u@\h \w]\$ '
